import { type Config as JestConfig } from '@jest/types';
import { type RollupOptions } from 'rollup';
import { type RawCompilerOptions } from 'ts-jest';
import { type ProjectJestConfig } from './jest/project-jest-config.js';
import { type PackageJson } from './package/package.json.js';
import { type ProjectPackage } from './package/project-package.js';
import { type ProjectConfig } from './project-config.js';
import { type ProjectRollupConfig } from './rollup/project-rollup-config.js';
import { type ProjectTypescriptConfig } from './typescript/project-typescript-config.js';

/**
 * Defaults for project development tools.
 *
 * The tools are actually created by static methods of corresponding tool classes. The values in this configuration
 * are used as defaults for corresponding tools.
 */
export type ProjectToolDefaults = {
  readonly [K in keyof ProjectToolsInit]?: ProjectToolType<ProjectToolsInit[K]>;
};

export type ProjectToolType<
  TInit extends ((project: ProjectConfig) => object) | object | undefined,
> = TInit extends (project: ProjectConfig) => infer TTool ? TTool : TInit;

/**
 * Development tools specifiers for the project.
 *
 * Each property contains either project tool specifier, or a function creating such tool for the given project.
 */
export interface ProjectToolsInit {
  /**
   * Initializer of Jest configuration of the project.
   *
   * One of:
   *
   * - Jest configuration instance.
   * - Jest initialization options {@link ProjectJestConfig#extendOptions extending} autogenerated ones.
   * - Function creating Jest configuration.
   */
  readonly jest?:
    | JestConfig.InitialOptions
    | ProjectJestConfig
    | ((project: ProjectConfig) => ProjectJestConfig)
    | undefined;

  /**
   * Initializer of package configuration of the project.
   *
   * One of:
   *
   * - Package configuration instance.
   * - Raw `package.json` contents, or promise-like instance resolving to ones
   *   {@link ProjectPackage#extendPackageJson extending} autoloaded one.
   * - Function creating package configuration.
   */
  readonly package?:
    | PackageJson
    | PromiseLike<PackageJson>
    | ProjectPackage
    | ((project: ProjectConfig) => ProjectPackage)
    | undefined;

  /**
   * Initializer of Rollup configuration of the project.
   *
   * One of:
   *
   * - Rollup initialization options {@link ProjectRollupConfig#extendOptions extending} default ones.
   * - Rollup configuration instance.
   * - Function creating Rollup configuration.
   */
  readonly rollup?:
    | RollupOptions
    | ProjectRollupConfig
    | ((project: ProjectConfig) => ProjectRollupConfig)
    | undefined;

  /**
   * Initializer of TypeScript configuration of the project.
   *
   * One of:
   *
   * - TypeScript compiler options to {@link ProjectTypescriptConfig#extendOptions extend} the ones loaded from
   *   `tsconfig.json` file.
   * - TypeScript configuration instance.
   * - Function creating TypeScript configuration.
   */
  readonly typescript?:
    | RawCompilerOptions
    | ProjectTypescriptConfig
    | ((project: ProjectConfig) => ProjectTypescriptConfig)
    | undefined;
}
