import { type Config as JestConfig } from '@jest/types';
import { ProjectJestConfig } from './jest/project-jest-config.js';
import { PackageJson } from './package/package.json.js';
import { ProjectPackage } from './package/project-package.js';
import { ProjectConfig } from './project-config.js';
import { ProjectRollupConfig, ProjectRollupSpec } from './rollup/project-rollup-config.js';
import {
  ProjectTypescriptConfig,
  ProjectTypescriptSpec,
} from './typescript/project-typescript-config.js';

/**
 * Defaults for project development tools.
 *
 * The tools are actually created by static methods of corresponding tool classes. The values in this configuration
 * are used as defaults for corresponding tools.
 */
export type ProjectToolDefaults = {
  readonly [K in keyof ProjectToolsInit]?: ProjectToolType<ProjectToolsInit[K]>;
};

export type ProjectToolType<
  TInit extends ((project: ProjectConfig) => object) | object | undefined,
> = TInit extends (project: ProjectConfig) => infer TTool ? TTool : TInit;

/**
 * Development tools specifiers for the project.
 *
 * Each property contains either project tool specifier, or a function creating such tool for the given project.
 */
export interface ProjectToolsInit {
  /**
   * Initializer of Jest configuration of the project.
   *
   * One of:
   *
   * - Jest configuration instance.
   * - Jest initialization options {@link ProjectJestConfig#extendOptions extending} autogenerated ones.
   * - Function creating Jest configuration.
   */
  readonly jest?:
    | JestConfig.InitialOptions
    | ProjectJestConfig
    | ((project: ProjectConfig) => ProjectJestConfig)
    | undefined;

  /**
   * Initializer of base project's package configuration.
   *
   * One of:
   *
   * - Package configuration instance.
   * - Raw `package.json` contents, or promise-like instance resolving to ones
   *   {@link ProjectPackage#extendPackageJson extending} autoloaded one.
   * - Function creating package configuration.
   */
  readonly package?:
    | PackageJson
    | PromiseLike<PackageJson>
    | ProjectPackage
    | ((project: ProjectConfig) => ProjectPackage)
    | undefined;

  /**
   * {@link ProjectRollupConfig.of Specifier} of Rollup configuration of the project.
   */
  readonly rollup?: ProjectRollupSpec | ((project: ProjectConfig) => ProjectRollupConfig);

  /**
   * {@link ProjectTypescriptConfig.of Specifier} of project's TypeScript configuration.
   */
  readonly typescript?:
    | ProjectTypescriptSpec
    | ((project: ProjectConfig) => ProjectTypescriptConfig);
}
